name: Kimberly LeClair
favicon: null
layout_spectrum: 0.5095071215182543
typography_spectrum: 0.294354441575706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6541765569709241
  lightness: 0.818281423766166
  saturation: 0.39031655131839216
  rhythmicContrast: 0.26348752714693546
purpose: []
